#!/bin/sh

# Mock cat.

# The MIT License (MIT)
#
# Copyright (c) 2016 Susam Pal
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


# This script prints a single line of output that contains each
# command-line argument surrounded in double-quotes. This script is used
# as VIM_CMD for many tests where the command-line arguments Vim is
# invoked with needs to be verified.


# Begin creating a result string with the first argument in double-quotes.
[ $# -gt 0 ] && args="\"$1\"" && shift

# Append each remaining argument within double-quotes to the result string.
while [ $# -gt 0 ]
do
    args="$args \"$1\"" && shift
done

# Finally print the result string.
printf "%s\n" "$args"
